[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dev_loot = "8ftYsC7GGH6sh1MQw81TQBc6W4TR3gsLp7it4vFNDxUu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
