[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_marketplace = "EZxVqcFjg2yg1ZQWeCaxEQ1N6EH3SR45cedS2LvDBJ8n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
