[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "8yXr4yGrfLAAv8bN3cDHeLKZRBmRbMWbKrqcwkK8VEG6"

[programs.devnet]
anchor_escrow = "8yXr4yGrfLAAv8bN3cDHeLKZRBmRbMWbKrqcwkK8VEG6"

[programs.mainnet]
anchor_escrow = "8yXr4yGrfLAAv8bN3cDHeLKZRBmRbMWbKrqcwkK8VEG6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
