[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking = "4EPq6SFvNwjPhZjCFfHStd5bw1ryGXM3d2cAj8ja9o5L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
